[project]
name = "hedypet-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "extra-streamlit-components>=0.1.81",
    "plotly>=6.3.0",
    "seaborn>=0.13.2",
    "streamlit>=1.48.1",
]
